let jokes = [
    "Why did the scarecrow become a successful politician? Because he was outstanding in his field!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What do you call fake spaghetti? An impasta!",
    "Why don't scientists trust stairs? Because they're always up to something!",
    "Why was the math book sad? Because it had too many problems.",
    "What's the difference between ignorance and apathy? I don't know, and I don't care.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "What's the best time on a clock? 6:30, hands down!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "Why couldn't the bicycle stand up by itself? It was two-tired!",
    "Why was the belt arrested? It was holding up a pair of pants!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What do you call fake spaghetti? An impasta!",
    "Why don't scientists trust stairs? Because they're always up to something!",
    "Why was the math book sad? Because it had too many problems.",
    "What's the difference between ignorance and apathy? I don't know, and I don't care.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "What's the best time on a clock? 6:30, hands down!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "Why couldn't the bicycle stand up by itself? It was two-tired!",
    "Why was the belt arrested? It was holding up a pair of pants!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
    "Why don't some couples go to the gym? Because some relationships don't work out!",
    "What do you call fake spaghetti? An impasta!",
    "Why don't scientists trust stairs? Because they're always up to something!",
    "Why was the math book sad? Because it had too many problems.",
    "What's the difference between ignorance and apathy? I don't know, and I don't care.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don't eggs tell jokes? Because they might crack up!",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "What's the best time on a clock? 6:30, hands down!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "Why couldn't the bicycle stand up by itself? It was two-tired!",
    "Why was the belt arrested? It was holding up a pair of pants!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
  ];
    
  let index = Math.floor(Math.random()*jokes.length-1);
  console.log(index)
  myjokes.innerHTML = jokes[index];
    